Allow Wiremod and Seats to be destroyed
CFC-Servers/simple_prop_damage pull request #7
Opened 2020-07-25 02:09 UTC by TechnichalDoge

On CFC, (deadly) contraptions like tanks, planes, turrets, etc, usually rely on chairs and/or wiremod components like gates or e2, SPD was not able to destroy these important parts of these contraptions. This PR changes it so that wiremod entities and seats are able to be destroyed either via bullets, or if an explosion has line of sight to the chair or wiremod entity. Having the explosion only be able to affect the chair or entity if it has line of sight is important, as if we just plopped in the ability to destroy them without such, an explosion outside of a tank would kill them. 
This new added ability will also be able to help in the future, if infantry weapons are able to penetrate and explode within a tank, (which i have an idea for but is out of the scope of this PR), it would be able to de-brain a tank, and forcing the builder to actually not splerg the brains onto the base prop, and actually put it somewhere protected.

In testing this, we have found a slight issue with chairs in general, as shooting them does not pulse the "EntityTakeDamage" hook, so shooting chairs doesn't really make them take damage, and explosions usually work on most chairs. This is most likely a GMod bug or chairs being cursed. Although this slight issue does not affect much, as if you're able to directly shoot a chair, you are able to kill the driver.
CC @Deconkle @hexwolf (whoever he may be)

2020-07-25 03:00 UTC, plally requested changes
i would be concerned about the impact on performance running many traces might have, although it would be limited to just a few entity types (so its probably not too bad)

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +local affectedEnts = {}
define table like so plz
```lua
local tbl = {
    key1 = true,
    key2 = true
}
```

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +
```suggestion
```

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +
```suggestion
```

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +
```suggestion
```

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +function IsSPDAffectedEntity( ent )
it might be better to just be consistent with spd's naming and call it `spdIsAffectedEntity`

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +    local losTraceData = {}
```lua
tbl = {
    start = v,
    endpos = something
}
```

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +    local entPosition = ent:GetPos() or Vector( 0, 0, 0 )
will GetPos ever return a falsey value??

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +local function isInLineOfSight( sVector, ent )
sVector? does the s stand for start? if so just write `start` or `startVector`

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +function IsSPDAffectedEntity( ent )
same with `IsSPDAffectedLOSEntity`

2020-07-25 03:00 UTC, plally commented on lua/spd/server/sv_spd.lua
> +    local condForSpecial = not isInLineOfSight( dmg:GetDamagePosition(), ent ) and dmg:IsDamageType( DMG_BLAST )
wouldnt this call a relatively expensive function when it might not even be needed
should check if the damage type is DMG_BLAST and it is an "affected LOS Entity" and only run traces if those 2 things are true

2020-07-25 03:01 UTC, TechnichalDoge commented on lua/spd/server/sv_spd.lua
> +local affectedEnts = {}
Should probably clarify this in styleguide, too.

2020-07-25 03:20 UTC, TechnichalDoge commented on lua/spd/server/sv_spd.lua
> +function IsSPDAffectedEntity( ent )
i would think global functions would be pascal case, too?

2020-07-25 03:21 UTC, TechnichalDoge commented on lua/spd/server/sv_spd.lua
> +    local entPosition = ent:GetPos() or Vector( 0, 0, 0 )
probably not.

2020-07-25 03:21 UTC, TechnichalDoge commented on lua/spd/server/sv_spd.lua
> +    local condForSpecial = not isInLineOfSight( dmg:GetDamagePosition(), ent ) and dmg:IsDamageType( DMG_BLAST )
actually, ye will change

2020-07-25 03:35 UTC, plally commented on lua/spd/server/sv_spd.lua
> +function IsSPDAffectedEntity( ent )
this project currently doesnt conform to cfc style guidelines so its better to be consistent unless the entire project is changed
(which probably should not be done in this pr)

2020-12-19 01:30 UTC, brandonsturgeon commented
Converting this to a draft because SPD is up in the air but I don't want to lose this progress if we decide to use it for a future server.

2020-12-19 05:43 UTC, TechnichalDoge commented
Odd to see this still active, lol, good to know there is still btk reg. :)

On Fri, Dec 18, 2020 at 7:30 PM Brandon Sturgeon <notifications@github.com>
wrote:

> Converting this to a draft because SPD is up in the air but I don't want
> to lose this progress if we decide to use it for a future server.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CFC-Servers/simple_prop_damage/pull/7#issuecomment-748398269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD6ZCEVTYIG3IGQ4U4BAUK3SVP63LANCNFSM4PHHAP6A>
> .
>

2021-11-25 09:52 UTC, closed without merging

2021-11-25 09:53 UTC, brandonsturgeon commented
We've officially dropped SPD - we'll be sure to revisit this if we find that SPD is better suited on a different server 👍